# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastGGM <- function(x, lambda = NA_real_) {
    .Call('FastGGM_FastGGM', PACKAGE = 'FastGGM', x, lambda)
}

FastGGM_edges <- function(x, pairs, lambda = NA_real_) {
    .Call('FastGGM_FastGGM_edges', PACKAGE = 'FastGGM', x, pairs, lambda)
}

FastGGM_Parallel <- function(x, lambda = NA_real_) {
    .Call('FastGGM_FastGGM_Parallel', PACKAGE = 'FastGGM', x, lambda)
}

